#! /bin/bash

# Script to check if all the gnuradio files gets downloaded using the new tunneling and proxy configuration 

proxy="netmon.iitb.ac.in:80"

# Setting the gitproxy
git config --global core.gitproxy $PWD/git-proxy.sh

# Setting the git proxy via http and https

while read line
do
	auth=$line
done < "authfile"

git config --global http.proxy http://$auth@$proxy
git config --global https.proxy http://$auth@$proxy


